package org.csc133.a3;


import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import org.csc133.a3.main.Game;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class AppMain {

    public void init(Object context) {
        Resources theme;
        theme = UIManager.initFirstTheme("/theme");
    }
    
    public void start() {
        new Game();
    }
}
